### PR TITLE
Implement custom Quit / Close Menu keybind

### PR DESCRIPTION
**Pull request by dc138**
This commit adds support for rebinding the quit / close menu key.

### CODE REVIEW

**Comment by Minenash** [comment]
Sorry for the wait, somehow I "unwatched" this repo.

I've thought about adding this in before, the main reason I didn't, is that it felt such an important key, that it may cause problems if accidentally unbound. Speaking of binding, since esc unbinds a key, you couldn't press esc to bind it

**Comment by dc138** [comment]
Maybe we could add a warning screen when leaving the key-binds menu with the key unbound, to prevent the user from accidentally leaving it unbound, or maybe just binding it to escape if it is the case. Regarding not being able to bound it, you can always click reset to set it back to its default value.

**Comment by Minenash** [comment]
Hmm, what if the keybind in the controls is an alias, so escape still works, but so does whatever the user enters?

**Comment by Minenash** [comment]
PR #7 did not implement this

**Comment by Minenash** [comment]
I was expecting more conflicts than actually existed, so the code I'm about to push is based from this PR (just with it being an alias instead of an override), it'll be in tonight's released

**Pull request closed without merging**
